### ISSUE TITLE
Incorrect width

### ISSUE THREAD

**Issue by a-x-** [Hacker0x01/react-datepicker#1027]
There is incorrect width when datepicker is nested in narrow absolute block (popup: [react-popover](https://github.com/littlebits/react-popover) 0.4.9)

I migrated from 0.34.0 to 0.54.0.

I hotfixed it with:
```css
.react-datepicker-popper {
  min-width: 300px
}
```

<img width="366" alt="screen shot 2017-09-19 at 11 14 54" src="https://user-images.githubusercontent.com/6201068/30582276-cdbbf2fe-9d2b-11e7-9c68-48ad4c9160bd.png">
