### ISSUE TITLE
Wrong position datepicker when custom the scrollbar

### ISSUE THREAD

**Issue by nghiepit** [Hacker0x01/react-datepicker#1191]
Hi guys,

I have used https://github.com/utatti/perfect-scrollbar to custom scrollbar of `container` page.

```html
<body>
   <div class="container">
      // something else
     <Datepicker />
   </div>
</body>
```

```css
.container {
   height:100vh; // required for scrollbar
}
```
That has made position datepicker incorrect.

![image](https://user-images.githubusercontent.com/4768095/34428520-316167b4-ec80-11e7-9e68-aa52b694dda9.png)

Thanks in advance.
