### ISSUE TITLE
incorrect popper position

### ISSUE THREAD

**Issue by borm** [Hacker0x01/react-datepicker#1340]
### Steps to reprodcue
Go to [https://reactdatepicker.com/](https://reactdatepicker.com/)

Open developer tools

set styles to first node selector `hero__example`
```css
{
    position: absolute;
    top: 0;
    right: 0;
}
```

Try open picker
![image](https://user-images.githubusercontent.com/4027842/38163024-c8d42d6c-34f5-11e8-8f24-01d7686bc88f.png)
