### ISSUE TITLE
Incorrect border-radius/height on time-only picker

### ISSUE THREAD

**Issue by wustep** [Hacker0x01/react-datepicker#1788]
<img width="712" alt="Screen Shot 2019-06-17 at 11 54 22 AM" src="https://user-images.githubusercontent.com/6259534/59618794-f21f4180-90f6-11e9-880b-455442e9ac97.png">

### Expected behavior

First selected time's border should be square.

### Actual behavior

Selected time's border is rounded :'(

### Steps to reproduce

1. Make a Select Time Only Datepicker, e.g.:
```jsx
<DatePicker
    selected={this.state.startDate}
    onChange={this.handleChange}
    showTimeSelect
    showTimeSelectOnly
    timeIntervals={15}
    dateFormat="h:mm aa"
    timeCaption="Time"
/>
```

2. Select the first time. 

### Fix

The fix I'm doing locally is:
```css
  .react-datepicker__time-box {
    border-radius-top: 0 /* Fix incorrect selected rounded border on time-box */;
  }
```
I think this can be applied [here in the codebase](https://github.com/Hacker0x01/react-datepicker/blob/master/src/stylesheets/datepicker.scss#L33).

## Height

Additionally, this height is slightly vertically off-center. Height can be unset [here in codebase](https://github.com/Hacker0x01/react-datepicker/blob/master/src/stylesheets/datepicker.scss#L278) or with styling: 

```css
.react-datepicker__time-list-item {
    height: unset !important;
}
```
