### ISSUE TITLE
Some layout issues on windows

### ISSUE THREAD

**Issue by bertyhell** [Hacker0x01/react-datepicker#1973]
**Describe the bug**
Right arrow is in the incorrect location and hour input doesn't have correct height for certain months

**To Reproduce**

1. Go to https://reactdatepicker.com/#example-include-times
2. open the dropdown
3. goto may 2020

**Expected behavior**
right button is in the correct location on windows and the hour picker is full height

**Screenshots**
![image](https://user-images.githubusercontent.com/1710840/69226288-2ef8d400-0b80-11ea-8a71-c4d0a3941070.png)

**Desktop (please complete the following information):**

- OS: windows 10 (1903)
- Browser chrome Version 78.0.3904.97 (Official Build) (64-bit)
- Version 2.10.0

**Additional context**
I was able to work around the issue with this code, although the height of the popup is higher than it should be for most months. It doesn't look broken with this workaround though:

```scss
.react-datepicker__navigation--next--with-time:not(.react-datepicker__navigation--next--with-today-button) {
	left: 180px;
}

.react-datepicker__time-container .react-datepicker__time .react-datepicker__time-box ul.react-datepicker__time-list {
  height: calc(195px + (1.7rem / 2)) !important;
	width: calc(100% - 1px);
}
```
