### ISSUE TITLE
Inline version selects multiple dates 

### ISSUE THREAD

**Issue by MD-AZMAL** [Hacker0x01/react-datepicker#2284]
**Describe the bug**
In Inline Version when you select some other date the initial selected date remains the same with blue background
**To Reproduce**

1. Go to 'inline version or inline portal version in docs'
2. Click on any date
4. See error when multiple dates are selected

**Expected behavior**
Only one date is supposed to be selected
**Screenshots**
![Screenshot from 2020-07-22 14-57-06](https://user-images.githubusercontent.com/33421347/88160168-ee2fee00-cc2b-11ea-90ab-671b8d20a54f.png)

**Desktop (please complete the following information):**

- OS: Ubuntu
- Browser Chrome

**Comment by jxa8057** [comment]
I'm also running into this, where the current day of the month always appears selected, event when changing months.

**Comment by MD-AZMAL** [comment]
@jxa8057 do let me know if you find any solution

**Comment by PoltP** [comment]
It can be easily reproduced using [demo](https://reactdatepicker.com/#example-inline-version) after "Next" or "Previous" button is clicked. This bug makes component unusable in production.

**Comment by MD-AZMAL** [comment]
@PoltP yes i think so, is there any work around ?

**Comment by PoltP** [comment]
@MD-AZMAL I have not found any usable workaround, now I've temporary disabled keyboard navigation using `disabledKeyboardNavigation` property.

**Comment by MD-AZMAL** [comment]
@PoltP okay got it! still keeping this issue please share if you find any other solution

**Comment by camilaazuma** [comment]
Same issue here, anyone got updates? 👀

**Comment by camilaazuma** [comment]
Hey @MD-AZMAL, made this is a workaround until the lib is properly fixed. Basically:

1. Make sure to have a `ref` to the calendar
2. Whenever a day is clicked, search for the `keyboard-selected` class and removes it from the element.
3. Then adds the same class to the current selected day

This only solves the layout issue. Focus is still on original `keyboard-selected` element.
Don't forget to declare the `selected` on your `useEffect`, so it triggers every time the date changes.

```
  useEffect(() => {
    if (inline) {
      const keyboardSelected = ref.current.calendar.componentNode.querySelector('.react-datepicker__day--keyboard-selected');
      const mouseSelected = ref.current.calendar.componentNode.querySelector('.react-datepicker__day--selected');

      if (keyboardSelected && mouseSelected) {
        keyboardSelected.classList.remove('react-datepicker__day--keyboard-selected');
        mouseSelected.classList.add('react-datepicker__day--keyboard-selected');
      }
    }
  }, [selected, inline]);

**Comment by Svish** [comment]
I don't think the issue here is actually multiple selected dates. It's that:

1.  `--keyboard-selected` looks way too similar to actually selected.
2. Using mouse to select a date, doesn't update/focus the keyboard selected date.

**Style**
This should be fixed for both inline and non-inline version; maybe use outline/border instead of just slightly lighter color?

**Selection**
For non-inline (see e.g. the "Don't hide calendar on date selection" sample) this does not seem to be an issue, the keyboard selected date changes to the one you select with the mouse, so following keyboard navigation "goes from" the one you clicked on.

For inline, however, the keyboard selected stays the same, regardless of mouse clicking or month changing. I feel it's OK for keyboard selection to stay when changing months (at least when style is updated to look less like a selected date). But when clicking on a day, the keyboard selection should also update and equal the selected date. If I click on the 5th, and then press right arrow, it should go to the 6th, not whatever was next last I used keyboard.

(hope all that made sense...?)

**Comment by MD-AZMAL** [comment]
@camilaazuma Thanks for the workaround i'll definitely try it!

@Svish Ya got your point it actually happens when selected from mouse

**Comment by stearruda** [comment]
Any news about this issue?
I believe it's almost impossible to target the style by CSS.

**Comment by Svish** [comment]
@stearruda We had to "re-do" the styling anyways to make it fit in with our design, but basically what we did was to simply remove the following styling, because we noticed our existing `:focus` styling still worked.

```css

.react-datepicker__day--keyboard-selected,
.react-datepicker__month-text--keyboard-selected,
.react-datepicker__quarter-text--keyboard-selected,
.react-datepicker__year-text--keyboard-selected {
  border-radius: 0.3rem;
  background-color: #2a87d0;
  color: #fff;
}

.react-datepicker__day--keyboard-selected:hover,
.react-datepicker__month-text--keyboard-selected:hover,
.react-datepicker__quarter-text--keyboard-selected:hover,
.react-datepicker__year-text--keyboard-selected:hover {
  background-color: #1d5d90;
}
```

So a workaround for you could be to override those with `initial` or `inherit` or `transparent` or whatever works. Just remember to have a `:focus` style still. We use this:

```less
:focus {
  outline: @color-focus auto 0.2em;
}
```
