### ISSUE TITLE
Some options for handling range outside of month

### ISSUE THREAD

**Issue by filingroove** [Hacker0x01/react-datepicker#2713]
**Is your feature request related to a problem? Please describe.**
I'm making a range select picker for my app and it behaves like this when selecting range across months
![](https://i.imgur.com/26KTFNe.png)

**Describe the solution you'd like**
I would like an option to handle this like in AirBnb datepicker
![](https://i.imgur.com/NPakahW.png)

In order to achieve this, I imagine:
1. Class `--is-range-selection` should not be applied to dates outside of month. 
2. Classes `--is-range-selection-end` and `--is-range-selection-start` should be added

Then I can apply styles to `:before` and `:after` to go slightly outside the node and apply gradient to it's bg.

**Describe alternatives you've considered**
Using `dayClassName` can work just fine if only we had some context passed in the arguments. Like:
```javascript
{
  'is-range-selection': true,
  'is-range-selection-end': true,
  ...
  // etc
}
```

**Comment by filingroove** [comment]
Mb I was too early to open the issue, but I managed to do this in css:

![](https://i.imgur.com/2nw7RIn.png)

I also feel like it's way dirtier than it needs to be, it's not in any way reliable and can be broken with any update. So I'm not closing the issue 🙂

A short piece of context:
```css
/* Make sure that only first outside month day is filled with gradient */
.react-datepicker__day--outside-month + .react-datepicker__day--outside-month:after {
  background: transparent !important;
}

/* For a part when range and selection range touch outside month (month end) */
.react-datepicker__day--in-range + .react-datepicker__day--outside-month:after {
  background: linear-gradient( 90deg, rgb(130,188,255), rgb(130,188,255) 5%, transparent );
}

.react-datepicker__day--in-selecting-range + .react-datepicker__day--outside-month:after {
  background: linear-gradient( 90deg, rgb(238,246,255), transparent );
}

/* For a part when outside month touches range and selecting range (month start)  */
.react-datepicker__day--outside-month + .react-datepicker__day--in-selecting-range:after,
.react-datepicker__day--outside-month + .react-datepicker__day--in-range:after {
  padding: 0px 6px 0px 36px;
  margin-left: -58px;
}

.react-datepicker__day--outside-month + .react-datepicker__day--in-range:not(.react-datepicker__day--outside-month):after {
  background: linear-gradient( 90deg, transparent 0%, rgb(130,188,255) 75% );
}

.react-datepicker__day--outside-month + .react-datepicker__day--in-selecting-range:not(.react-datepicker__day--outside-month):after {
  background: linear-gradient( 90deg,transparent 0%, rgb(238,246,255) 75% ) !important;
}
  
```
