### ISSUE TITLE
Datetime picker is not responsive

### ISSUE THREAD

**Issue by approached** [Hacker0x01/react-datepicker#2833]
**Describe the bug**
Datetime picker is not responsive.

**To Reproduce**
```js
                    <DatePicker
                        name={name}
                        placeholderText={placeHolder}
                        autoComplete="off"
                        selected={value}
                        onChange={onChange}
                        openToDate={openToDate}
                        locale="de"
                        showTimeSelect
                        dateFormat="Pp"
                        timeIntervals={15}
                        isClearable
                    />
```

**Screenshots**
![image](https://user-images.githubusercontent.com/3439330/112544481-57699180-8db7-11eb-93ee-087689451929.png)

**Desktop (please complete the following information):**
- OS: Mac
- Browser: chrome
- Version: 89.0.4389.90

**Comment by Dupflo** [comment]
@approached how dd you fixed that ? Same issue for me

**Comment by approached** [comment]
I use chakra ui and the css settings are crappy. This works me:
```css
/* time responsive settings */
.react-datepicker__time-container {
    width: 84px;
}

.react-datepicker__navigation--next--with-time:not(.react-datepicker__navigation--next--with-today-button) {
    right: 90px;
}
```
