### ISSUE TITLE
Current day highlighted across all months

### ISSUE THREAD

**Issue by qasimalyas** [Hacker0x01/react-datepicker#2930]
**Describe the bug**
Current day is selected across all months which is bad for UX. It can cause confusion making it look like two dats might have been selected. This has been raised multiple times but no real solution exists to disabled the highlighting. https://github.com/Hacker0x01/react-datepicker/issues/2376, https://github.com/Hacker0x01/react-datepicker/issues/2456

**To Reproduce**

1. Go to https://reactdatepicker.com/ where you'll see the default calendar open
![image](https://user-images.githubusercontent.com/85598/116974072-6ea07680-acb5-11eb-857c-e2924304ae17.png)
2. Click to go to next month
![image](https://user-images.githubusercontent.com/85598/116974094-7b24cf00-acb5-11eb-8296-da36fdd83c64.png)
3. You'll see day 4 being highlighted
4. This occurs for all months followed

**Expected behavior**
There shouldn't be any highlight dates.

**Screenshots**
See above

**Desktop (please complete the following information):**

Applicable on all browsers and devices

**Additional context**
This is confusing and disabling keyboard navigation seems to be the only option but that breaks accessibility. Ideally this shouldn't be happening or at the very least be an optional opt-in.

**Comment by relwiwa** [comment]
The highlighting is necessary to know where keyboard focus is. @martijnrusschen Probably it would be a good idea to change the styling to make it more different from the selected day styling?

A workaround is to change the styling via this class: .react-datepicker__day--keyboard-selected

**Comment by qasimalyas** [comment]
I don't have anything against keyboard focus - which is absolutely necessary for usability & accessibility. But I don't think this is about that. The issue is this:

1. todays date is 19 may 2021
2. As a user I click to open the date picker
3. 19th is selected by default
4. I click next month
5. The same date 19th is selected

I could be missing something but I don't see how this is useful. It adds to the confusion as I haven't even selected a date yet but it makes it seems so. If I change keyboard specific styling then that will change point 5 but will also affect any keyaboard navigation - which I don't want to do. 

I think the solution would be to exclude highlighting dates like this from future months. If its necessary for whatever reason then make it optional.

**Comment by relwiwa** [comment]
> 5. The same date 19th is selected
This is not correct. The day is not "selected", because in the input field is still 19 may 2021, not 19 june 2021.
There is a (probably too) subtle styling difference between the selected date and the highlighted date

**Comment by annika-linke** [comment]
This Problem is also appearing in the range datepicker. The Range gets highlighted in every month (even on the official docs page https://reactdatepicker.com/#example-date-range).

I found a workaround that fixes the problem for me. I will just assign my own classes and disable the problem causing styles.

```js
// value is a formik field value : string

const activeClass = (date: Date) => {
    const activeClass =
      date.getTime() === new Date(value).getTime()
        ? 'date-picker-field__active'
        : undefined;

    const startActiveClass =
      props?.startDate && date.getTime() === props?.startDate.getTime()
        ? 'date-picker-field__active--start'
        : undefined;

    const endActiveClass =
      props?.endDate && date.getTime() === props?.endDate.getTime()
        ? 'date-picker-field__active--end'
        : undefined;

    const rangeColor =
      props?.startDate &&
      props?.endDate &&
      date.getTime() >= props?.startDate.getTime() &&
      date.getTime() <= props?.endDate.getTime()
        ? 'date-picker-field__range'
        : undefined;

    // classNames from 'classnames'
    return classNames(
      rangeColor,
      startActiveClass,
      endActiveClass,
      activeClass,
    );
  };

return (
   <DatePicker
        {...rest}
        {...attributes}
        dayClassName={activeClass}
    />
);
```

```css
.date-picker-field__range {
  background-color: $pickerSelectionRangeColor !important;
}

.date-picker-field__active--start {
  background-color: $pickerSelectionRangeColor !important;
}

.date-picker-field__active--end {
  background-color: $pickerSelectionRangeColor !important;
}

.date-picker-field__active {
  background-color: $pickerSelectedColor !important;
  font-weight: var(--font-weight-black);
}

.react-datepicker__day--in-selecting-range,
.react-datepicker__month-text--in-selecting-range,
.react-datepicker__quarter-text--in-selecting-range,
.react-datepicker__year-text--in-selecting-range {
  background-color: transparent;
  color: $pickerTextColor;
}
```

**Comment by alex-streza** [comment]
@annika-linke your solution is great but I don't think it allows for updating the range while hovering to select a new date as in the example below.

![image](https://user-images.githubusercontent.com/72100849/120779989-8d499580-c51f-11eb-9304-428fee303bd6.png) ![image](https://user-images.githubusercontent.com/72100849/120780099-a4888300-c51f-11eb-9be1-da5df895e1c0.png)

The bug occurs when selecting a range and then editing either start or end dates

![image](https://user-images.githubusercontent.com/72100849/120780861-6770c080-c520-11eb-915f-68b06503cec2.png)

Even though I'm not hovering and the mouse is outside the calendar element react-datepicker__day--in-selecting-range class is added to every day in other months that is included within the original interval. 

![image](https://user-images.githubusercontent.com/72100849/120780910-7788a000-c520-11eb-9ad3-523cded48020.png)

![image](https://user-images.githubusercontent.com/72100849/120781039-9424d800-c520-11eb-9c6f-021c77314217.png)

**Comment by annika-linke** [comment]
@alex-streza that wasnt a dealbreaker for me, but its true! For me it was a better solution than the bug. It still needs to be handled in react-datepicker though...

**Comment by kidroca** [comment]
I think a similar issue is happening for the month picker as well - the selected month is highlighted for different years
Even when the date is disabled

![ezgif com-gif-maker](https://user-images.githubusercontent.com/12156624/122397889-0a462780-cf82-11eb-9eec-bd9f25a40865.gif)

**Comment by kidroca** [comment]
Related #3051

**Comment by mpiorowski** [comment]
Guys, try setting the selected value to sth, or null. Then this problem dissaper. I encounter similar probolem trying to set up datepicker for multiple day selection (not range). So from my another issue -> 
"I was able to do it using highlightDates option. On onChange concat or filter array of dates, set selectedDate to null, and style everything so that selected dates wont be visible. Now your highlightDates is the new value of datepicker."

**Comment by blackPantherOS** [comment]
The bad dates (one day difference) maybe Qt5 bug again. Few days ago all Plasma widget date is wrong date highlighted,

**Comment by snax4a** [comment]
Im also having this issue, when we are switching months, the focus should stay on arrow buttons so i don't understand why its keyboard selecting same day number

**Comment by JohnDDuncanIII** [comment]
@annika-linke @Bhavin789 per-https://github.com/Hacker0x01/react-datepicker/issues/2872#issue-853667583, I was able to fix this in my range datepicker by manually passing `minDate={null}`

https://user-images.githubusercontent.com/9257785/158491032-b78f959d-6956-4a80-aa56-09d685787c46.mov

first example in vid is the default `minDate` (i.e., not passing the prop down at all)
second example is `minDate={null}` behavior

**Comment by mohanbalasubramani** [comment]
> I think a similar issue is happening for the month picker as well - the selected month is highlighted for different years Even when the date is disabled
> 
> ![ezgif com-gif-maker](https://user-images.githubusercontent.com/12156624/122397889-0a462780-cf82-11eb-9eec-bd9f25a40865.gif)

any

**Comment by omer-alon** [comment]
> > I think a similar issue is happening for the month picker as well - the selected month is highlighted for different years Even when the date is disabled
> > ![ezgif com-gif-maker](https://user-images.githubusercontent.com/12156624/122397889-0a462780-cf82-11eb-9eec-bd9f25a40865.gif)
> 
> [Peter Velkov](https://github.com/kidroca) you got any solution for this?

Having the same issue too
It would be great if I could disable the highlighted month

**Comment by kidroca** [comment]
> > > I think a similar issue is happening for the month picker as well - the selected month is highlighted for different years Even when the date is disabled
> > 
> > [Peter Velkov](https://github.com/kidroca) you got any solution for this?
> 
> Having the same issue too It would be great if I could disable the highlighted month

@mohanbalasubramani, @omer-alon 
No we just live with it the way it is, for our use case it rarely happens and no one notices but QA

**Comment by Seijinx** [comment]
> > I think a similar issue is happening for the month picker as well - the selected month is highlighted for different years Even when the date is disabled
> > ![ezgif com-gif-maker](https://user-images.githubusercontent.com/12156624/122397889-0a462780-cf82-11eb-9eec-bd9f25a40865.gif)
> 
> [Peter Velkov](https://github.com/kidroca) you got any solution for this?

I used this workaround in CSS
````css
.react-datepicker__day--keyboard-selected,
.react-datepicker__month-text--keyboard-selected,
.react-datepicker__quarter-text--keyboard-selected,
.react-datepicker__year-text--keyboard-selected {
  border-radius: inherit;
  background-color: inherit;
  color: inherit;
}
.react-datepicker__month--selected,
.react-datepicker__month--in-selecting-range,
.react-datepicker__month--in-range,
.react-datepicker__quarter--selected,
.react-datepicker__quarter--in-selecting-range,
.react-datepicker__quarter--in-range {
  border-radius: 0.3rem;
  background-color: #216ba5;
  color: #fff;
}
````
