### ISSUE TITLE
version 4.1.1. year drop down header arrow not showing up

### ISSUE THREAD

**Issue by AvaniBataviya** [Hacker0x01/react-datepicker#3113]
**Describe the bug**
```
() => {
  const [startDate, setStartDate] = useState(new Date());
  return (
    <DatePicker
      selected={startDate}
      onChange={(date) => setStartDate(date)}
      showYearDropdown
      dateFormatCalendar="MMMM"
      yearDropdownItemNumber={15}
      scrollableYearDropdown
    />
  );
};
```
showYearDropdown = true and select year. Arrows not showing up in menu header

**To Reproduce**
1. Go to [react-datepicker year drop down](https://reactdatepicker.com/#example-year-dropdown)
2. Click on calendar of "year drop down" example and select year. (see attached screen short for more details)
3.  See error

**Expected behavior**
- up arrow in header and down arrow in footer must be there in year drop down menu.
**Screenshots**
![screenshot-newtab-2021 07 23-13_16_22](https://user-images.githubusercontent.com/35954780/126942716-e149e6c4-c349-4d40-a7f8-54e325c50377.png)

**Desktop (please complete the following information):**

- OS: [Ubuntu 16.04 LTS]
- Browser [chrome Version 91.0.4472.77]
- Version [4.1.1]

**Additional context**
It's version specific issue... In version 3.* it's working fine.

**Comment by vtaits** [comment]
Styles for workaround:

```css
.react-datepicker__navigation--years {
  background: none;
  line-height: 1.7rem;
  text-align: center;
  cursor: pointer;
  padding: 0;
  border: 0.45rem solid transparent;
  z-index: 1;
  height: 10px;
  width: 10px;
  text-indent: -999em;
  overflow: hidden;
  position: relative;
  display: block;
  margin-left: auto;
  margin-right: auto;
}

.react-datepicker__navigation--years.react-datepicker__navigation--years-upcoming {
  top: -4px;
  border-bottom-color: #ccc;
}

.react-datepicker__navigation--years.react-datepicker__navigation--years-previous {
  top: 4px;
  border-top-color: #ccc;
}
```

**Comment by Louis-T** [comment]
Hi, here are some styles for a quick workaround : 
```scss
.react-datepicker__navigation--years::before {
  border-color: #666;
  border-style: solid;
  border-width: 3px 3px 0 0;
  content: '';
  display: block;
  height: 9px;
  left: 11px;
  position: absolute;
  width: 9px;
}

.react-datepicker__navigation--years-upcoming::before {
  top: 17px;
  transform: rotate(315deg);
}

.react-datepicker__navigation--years-previous::before {
  top: 6px;
  transform: rotate(135deg);
}
```
(tested on v4.8.0)
