### ISSUE TITLE
there are no arrow symbols to represent while selecting the year from showYearDropDown property.

### ISSUE THREAD

**Issue by nishu-murmu** [Hacker0x01/react-datepicker#3672]
**Describe the bug**
while using the showYearDropDown property there are no up or down arrow symbols to click

**To Reproduce**
![Screenshot (12)](https://user-images.githubusercontent.com/71123337/174739349-df1f8263-7b36-4cd2-8726-98168d954a2c.png)

**Expected behavior**
To get those arrow symbols for convenience

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: Version 102.0.5005.115 (Official Build) (64-bit)

**Comment by Wissam-Yelhow** [comment]
Having the same issue here. Is there a prop we need to change to display these?

**Comment by khems** [comment]
I'm having the same issue. There are previous tickets for this https://github.com/Hacker0x01/react-datepicker/issues/3113 https://github.com/Hacker0x01/react-datepicker/issues/3028 but the css fixes don't work because the classes seem to have changed since?

**Comment by adershgr** [comment]
same issue , does anyone resolved it

**Comment by Louis-T** [comment]
Hi, here are some styles for a quick workaround :
```scss
.react-datepicker__navigation--years::before {
  border-color: #666;
  border-style: solid;
  border-width: 3px 3px 0 0;
  content: '';
  display: block;
  height: 9px;
  left: 11px;
  position: absolute;
  width: 9px;
}

.react-datepicker__navigation--years-upcoming::before {
  top: 17px;
  transform: rotate(315deg);
}

.react-datepicker__navigation--years-previous::before {
  top: 6px;
  transform: rotate(135deg);
}
```
(tested on v4.8.0)
