### ISSUE TITLE
Aria live message always displayed

### ISSUE THREAD

**Issue by okomarov** [Hacker0x01/react-datepicker#3924]
**Describe the bug**
After the commit for the Aria Live message https://github.com/Hacker0x01/react-datepicker/commit/3070e4afe78679bc2b57ad8cd1b8d83cd0dec0d4 I now get `Selected date: Thursday, February 2nd, 2023
` above my datepicker.

**To Reproduce**
Pick a date from a standard datepicker

**Expected behavior**
The aria live message should not show up on top of the datepicker

**Screenshots**

![aria](https://user-images.githubusercontent.com/3731173/217210935-56d4d443-99cd-424b-bb70-4c183dd37c53.gif)

**Desktop (please complete the following information):**

- OS: Mac OS latest
- Browser chrome
- Version latest

**Comment by okomarov** [comment]
The workaround is to add the css rule: 
```css
.react-datepicker__aria-live {
  display: none;
}
```

**Comment by vertic4l** [comment]
@martijnrusschen Please fix this. Latest version is not usable this way. And a css workaround shouldn't be the solution for this.

**Comment by Leningram** [comment]
Is there any plans to fix it? Why did it appeared? It also ruins tests for this component

**Comment by Svish** [comment]
Suddenly noticed this aria message here too now. Our CSS for the date-picker is fully custom, so we don't use any of the styles coming with the package. I'm guessing this is the case for others who see this text appearing too.

The actual fix for us with custom CSS is to copy the appropriate styles for this aria element:
```css
.react-datepicker__aria-live {
  position: absolute;
  clip-path: circle(0);
  border: 0;
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  width: 1px;
  white-space: nowrap;
}
```
Adding `display: none` is not good, as that will also remove the element for screen-readers, which I'm guessing was the whole point of adding this aria-live element to begin with?
