### ISSUE TITLE
Show only current visible month dates

### ISSUE THREAD

**Issue by syedzubair925** [Hacker0x01/react-datepicker#4079]
**I want to show only current visible month dates and exclude other dates from previous and next month
I want to use some simple method to do this task.**
![calender customize](https://github.com/Hacker0x01/react-datepicker/assets/127756189/ca98b6b8-55ac-47c5-923e-7dfd128cf528)

**Comment by GustavoLR548** [comment]
You can do that just by applying the following css:
```css
  .react-datepicker__day--outside-month {
    color: white;
  }
```

It will make the days outside of the current month "white" meaning that they will not be visible. It worked for me, hope it will work for you.
