### ISSUE TITLE
Bootstrap input-group CSS alignment

### ISSUE THREAD

**Issue by adamellsworth** [Hacker0x01/react-datepicker#484]
v.0.27.0
React v.15.0.1

---

I'm including the styles as noted in the docs:

```
require('react-datepicker/dist/react-datepicker.css');
```

There is a considerable disparity between the addon and the input style/alignment:

![screen shot 2016-05-12 at 3 42 50 pm](https://cloud.githubusercontent.com/assets/7034617/15232782/6b0b8286-1858-11e6-9e94-7ba466b76323.png)

**markup:**

``` javascript
<div className="input-group">
    <span className="input-group-addon">
        <i className="fa fa-calendar"></i>
    </span>
    <DatePicker
        selected={this.state.startDate}
        onChange={this.handleDateChange.bind(null, 'startDate')}
        placeholderText="Start Date &hellip;"
        className="form-control"/>
</div>
```

**Comment by rafeememon** [comment]
I believe this is because the top-level element of the `DatePicker` [isn't an `<input>`, it's a `<div>`](https://github.com/Hacker0x01/react-datepicker/blob/v0.27.0/src/datepicker.jsx#L198).  The only thing preventing us from changing it to an input right now is support for the clear button; however, supporting it in its current form is pretty restricting (because of cases like this issue), and it's not too difficult to implement outside of this library.  @martijnrusschen do you have any thoughts here?

**Comment by ryanzec** [comment]
I have the same problem with this.

A temporary hacky workaround I have found is to add this scss:

```scss
//NOTE: this is needed in order to make react-datepicker work with bootstrap's input group / input group addon functionatily
.react-datepicker__input-container {
  width: 100%;

  //NOTE: using table instead of block as it is needed in order to make this element set the height since the input is floating
  display: table;

  input {
    border-radius: $input-border-radius;
  }
}

.form-inline {
  .react-datepicker__input-container {
    width: auto;
    display: inline;
  }
}
```

This works fine for regular form elements however when you use inline form elements, that is where the hacky part come into play.  When using inline form elements, the height of the `react-datepicker__input-container` becomes messed up and does not reflect the height of the elements within.  In order to work around that, you can use the `popoverTargetOffset` property of `react-datepicker` to align the date picker itself properly.

@martijnrusschen I would be in favor of removing the clear functionality because as @rafeememon said, that is not very difficult functionality to implement manually and it would make this component more flexible to work with.  While my hacky solution works, I would not want it to be a long term solution as it would be very prone to breaking as styles are tweaked.

**Comment by aleccool213** [comment]
+1

**Comment by jochenberger** [comment]
I use a `customInput` that uses http://react-bootstrap.github.io/ for this use case:
```javascript
const InputWithButton = (props)=>{
  return(
    <InputGroup>
      <FormControl onClick={props.onClick} value={props.value} onChange={props.onChange} disabled={props.disabled} />
      <InputGroup.Button>
        <Button onClick={props.onClick} disabled={props.disabled}><Glyphicon glyph="calendar" /></Button>
      </InputGroup.Button>
    </InputGroup>
  );
};
```
and then

```javascript
<DatePicker customInput={<InputWithButton />} ... />
```
Maybe some custom input implementations could be provided with `react-datepicker`, this one would need a dependency on react-bootstrap though.

**Comment by jochenberger** [comment]
See http://codepen.io/jochenberger/pen/ENRNZN for an example.

**Comment by HadiAkmal** [comment]
@jochenberger 

I test your codepen and the selected date did not appear in the input field? Why is that?

**Comment by jochenberger** [comment]
Because there is no change handler specified on the `DatePicker`

**Comment by adamellsworth** [comment]
For those whom the above solution did not work, this kind of works for me, although it does shrink the entire form group:

```scss
.react-datepicker__input-container input.form-control {
    margin-bottom: -5px !important;
}
```
