### ISSUE TITLE
Month selectors not displaying, even without min or max date

### ISSUE THREAD

**Issue by RyanNovas** [Hacker0x01/react-datepicker#719]
I am rendering this element:

 ``` <DatePicker className="due-date-input" onChange={this.handleChange} placeholderText={this.formattedForHumanDate(this.state.startDate)}/>```

and in the browser it looks like this:

![screen shot 2017-01-24 at 6 14 52 pm](https://cloud.githubusercontent.com/assets/6655439/22271131/0f789804-e261-11e6-97f8-1aa3e34612b0.png)

I cannot figure out why the month selector arrows are not showing up. From the docs, it looks like they should be default.

**Comment by mgrdevport** [comment]
Any messages in the console?
Any changes on the css definition?
Does the document contain any element like the following if the calendar is popped out?
````html
<a class="react-datepicker__navigation react-datepicker__navigation--previous">
````
Is the following css definition present on the page?
```css
.react-datepicker__navigation--previous {
    left: 10px;
    border-right-color: #ccc;
}
.react-datepicker__navigation {
    line-height: 1.7rem;
    text-align: center;
    cursor: pointer;
    position: absolute;
    top: 10px;
    width: 0;
    border: 0.45rem solid transparent;
    z-index: 1;
}
```
